// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ehdayruzrgemvnklyilu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVoZGF5cnV6cmdlbXZua2x5aWx1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIxNTcwNTQsImV4cCI6MjA2NzczMzA1NH0.DYk-1zRbnq3UTlBPUeRrrUR-iwXOXnDXr2Zer3fhR0Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});